######################################################
##          SHOCKWAVES CONFIGURATION FILE           ##
## File must be called `shockwaves.toml` and placed ##
## in either the configuration directory or the     ##
## wavesource directory.                            ##
######################################################


## By default, the "error" style is propagated upwards from the subsignals.
## This behaviour can be turned off:
# propagate_errors = false

### Numbers are rendered using spacers to make them more legible.
### These can be specified from within Haskell, but this behaviour may be
### overwritten per number type. By default, signed and unsigned decimal
### numbers use [3,"_"] (an underscore every 3 digits) and other types use
### [4,"_"]. Use [0,""] to turn off spacers alltogether.
#override_sig_spacer = [3,"'"]
#override_uns_spacer = [3,"'"]
#override_hex_spacer = [4,"'"]
#override_oct_spacer = [4,"'"]
#override_bin_spacer = [4,"'"]

### A configuration may link one or more style config files.
### The paths may be relative, and the file extension (.toml) may be left out.
### Relative paths are taken relative to the configuration directory, unless they
### start with `./`, in which case they are taken relative to the source file.
### Style files are applied left-to-right, starting with those listed in the global
### configuration.
###
### Style files take the form `var = value` where the value can be:
### - a hexadecimal color code string, i.e. `red = "#f00"`
### - a dollar sign followed by a different var, i.e. `bool_false = "$red"`
### - one of the strings "NORMAL", "WARN", "ERROR"
### - a list of multiple variables, in which case the first defined value is
###   used, i.e. `bool_false = ["$gray","NORMAL"]`
#style = ["./shockwaves_style"]