
name: 'cargo-fmt'

on:
  push:
    paths:
      - 'surfer_shockwaves/**'
  pull_request:
    paths:
      - 'surfer_shockwaves/**'
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check formatting
        run: |
          cd $GITHUB_WORKSPACE/surfer_shockwaves
          cargo fmt --check
